apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: applemandarine.store
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: main-front
            port:
              number: 80
  # - host: movie.applemandarine.store
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: main-front
  #           port:
  #             number: 80
  # - host: article.applemandarine.store
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: article-front
  #           port:
  #             number: 80
